language: android
env:
  matrix:
    - ANDROID_SDKS=android-22,sysimg-22 ANDROID_TARGET=android-22 ANDROID_ABI=armeabi-v7a

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    # - tools

    # The BuildTools version used by your project
    - build-tools-22.0.1

    # The SDK version used to compile your project
    - android-22

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-22

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-22
    - sys-img-x86-android-22

notifications:
  email: false

script:
  "./gradlew build"

#before_script:
#  # Create and start emulator
#  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
#  - emulator -avd test -no-skin -no-audio -no-window &
#  - adb wait-for-device
#  - adb shell input keyevent 82 &


#  before_install:
#
#      # for gradle output style
#      - export TERM=dumb
#
#      # environment info
#      - ./gradlew -v
#      - uname -a
#
#  # Let's try to build...
#  script: ./gradlew clean build
#  script: ./gradlew connectedAndroidTest
